import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

type Lang = 'fa' | 'en';

interface LanguageContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Lang, Record<string, string>> = {
  fa: {
    'nav.home': 'خانه',
    'nav.about': 'درباره ما',
    'nav.contact': 'تماس',
    'nav.bloggerLogin': 'ورود بلاگر',
    'nav.businessLogin': 'ورود بیزینس',
    'nav.adminEntry': 'ورود ادمین',
    'hero.title': 'اتصال هوشمند بلاگرها و برندها',
    'hero.subtitle': 'همکاری مستقیم، امن، بدون واسطه',
    'hero.bloggerCard': 'ورود بلاگرها',
    'hero.businessCard': 'ورود کسب‌وکارها',
    'hero.adminCard': 'ورود ادمین',
    'hero.bloggerDesc': 'پروفایل بسازید و با برندها همکاری کنید',
    'hero.businessDesc': 'بلاگر مناسب کمپین خود را پیدا کنید',
    'hero.adminDesc': 'دسترسی موقت برای پیش‌نمایش داشبوردها',
    'stats.users': 'کاربر فعال',
    'stats.brands': 'برند همکار',
    'stats.campaigns': 'کمپین موفق',
    'how.title': 'چطور کار می‌کنه؟',
    'how.step1.title': 'کشف و انتخاب',
    'how.step1.desc': 'بلاگرها و برندهای مناسب خود را پیدا کنید',
    'how.step2.title': 'هماهنگی و همکاری',
    'how.step2.desc': 'شرایط همکاری را مشخص و توافق کنید',
    'how.step3.title': 'اجرای کمپین',
    'how.step3.desc': 'کمپین را اجرا کنید و نتایج را دنبال کنید',
    'features.title': 'امکانات پلتفرم',
    'features.security': 'امنیت کامل',
    'features.securityDesc': 'تمام اطلاعات و تراکنش‌ها با بالاترین سطح امنیتی محافظت می‌شوند',
    'features.analytics': 'داشبورد تحلیلی',
    'features.analyticsDesc': 'آمار و تحلیل‌های دقیق از عملکرد کمپین‌ها',
    'features.directComm': 'ارتباط مستقیم',
    'features.directCommDesc': 'بدون واسطه، مستقیم با طرف مقابل ارتباط برقرار کنید',
    'features.profile': 'پروفایل حرفه‌ای',
    'features.profileDesc': 'پروفایل کامل و حرفه‌ای برای نمایش توانایی‌ها',
    'about.title': 'درباره بلاگرها',
    'about.desc': 'بلاگرها یک مارکت‌پلیس هوشمند است که بلاگرها و اینفلوئنسرها را به برندها متصل می‌کند.',
    'about.bloggerBenefit': 'برای بلاگرها: درآمدزایی پایدار و دسترسی به برندهای معتبر',
    'about.brandBenefit': 'برای برندها: دسترسی به شبکه گسترده‌ای از بلاگرهای حرفه‌ای',
    'contact.title': 'تماس با ما',
    'contact.name': 'نام',
    'contact.email': 'ایمیل',
    'contact.message': 'پیام',
    'contact.send': 'ارسال پیام',
    'contact.success': 'پیام شما با موفقیت ارسال شد!',
    'footer.quickLinks': 'لینک‌های سریع',
    'footer.contactInfo': 'اطلاعات تماس',
    'footer.email': 'info@bloggerha.com',
    'footer.phone': '۰۲۱-۱۲۳۴۵۶۷۸',
    'footer.address': 'تهران، ایران',
    'footer.copyright': '© ۱۴۰۴ بلاگرها. تمام حقوق محفوظ است.',
    'footer.newsletter': 'پیام به ادمین',
    'footer.newsletterPlaceholder': 'ایمیل خود را وارد کنید',
    'footer.newsletterSend': 'ارسال',
    'register.blogger.title': 'ثبت‌نام بلاگر',
    'register.business.title': 'ثبت‌نام کسب‌وکار',
    'register.name': 'نام کامل',
    'register.email': 'ایمیل',
    'register.phone': 'شماره تلفن',
    'register.password': 'رمز عبور',
    'register.description': 'درباره خودتان',
    'register.instagram': 'لینک اینستاگرام',
    'register.category': 'دسته‌بندی',
    'register.submit': 'ثبت‌نام',
    'register.back': 'بازگشت',
    'register.success': 'ثبت‌نام با موفقیت انجام شد!',
    'register.categories.lifestyle': 'سبک زندگی',
    'register.categories.tech': 'تکنولوژی',
    'register.categories.food': 'غذا و آشپزی',
    'register.categories.fashion': 'مد و فشن',
    'register.categories.travel': 'سفر و گردشگری',
    'register.categories.beauty': 'زیبایی و آرایشی',
    'auth.login': 'ورود',
    'auth.signup': 'ثبت‌نام',
    'auth.email': 'ایمیل',
    'auth.password': 'رمز عبور',
    'auth.username': 'نام کاربری',
    'auth.selectRole': 'شما کدام هستید؟',
    'auth.blogger': 'بلاگر',
    'auth.business': 'کسب‌وکار',
    'auth.loginSuccess': 'ورود موفق!',
    'auth.signupSuccess': 'ثبت‌نام موفق!',
    'auth.logout': 'خروج',
    'auth.or': 'یا',
    'auth.noAccount': 'حساب ندارید؟',
    'auth.hasAccount': 'حساب دارید؟',
    // Admin
    'admin.temp': 'دسترسی موقت',
    'admin.title': 'می‌خواهید وارد کدام داشبورد شوید؟',
    'admin.subtitle': 'این دسترسی فقط برای پیش‌نمایش طراحی است',
    'admin.bloggerDash': 'ورود به داشبورد بلاگر',
    'admin.bloggerDesc': 'مشاهده داشبورد اینفلوئنسر',
    'admin.businessDash': 'ورود به داشبورد کسب‌وکار',
    'admin.businessDesc': 'مشاهده داشبورد برند',
    // Blogger Dashboard
    'dash.greeting': 'سلام،',
    'dash.welcomeMsg': 'فرصت‌های جدید منتظر شماست!',
    'dash.home': 'خانه',
    'dash.explore': 'کاوش',
    'dash.campaigns': 'کمپین‌ها',
    'dash.profile': 'پروفایل',
    'dash.currentInvite': 'دعوت فعلی',
    'dash.accept': 'قبول',
    'dash.decline': 'رد',
    'dash.invitations': 'دعوت‌نامه‌ها',
    'dash.toConfirm': 'در انتظار تأیید',
    'dash.toVisit': 'برای بازدید',
    'dash.completed': 'تکمیل شده',
    'dash.featured': 'کمپین‌های ویژه',
    'dash.pending': 'در انتظار',
    'dash.accepted': 'پذیرفته شده',
    'dash.scheduled': 'زمان‌بندی شده',
    'dash.rejected': 'رد شده',
    'dash.noData': 'هنوز موردی وجود ندارد',
    'dash.filters': 'فیلترها',
    'dash.category': 'دسته‌بندی',
    'dash.location': 'مکان',
    'dash.editProfile': 'ویرایش پروفایل',
    'dash.save': 'ذخیره',
    'dash.bio': 'بیوگرافی',
    'dash.instagram': 'اینستاگرام',
    'dash.engagement': 'تعامل',
    'dash.profileHealth': 'سلامت پروفایل',
    'dash.performance': 'عملکرد',
    'dash.followers': 'فالوورها',
    'dash.responseRate': 'نرخ پاسخ',
    'dash.profileScore': 'امتیاز پروفایل',
    'dash.applyNow': 'درخواست',
    'dash.searchCampaigns': 'جستجوی کمپین...',
    'dash.confirmAttendance': 'تأیید حضور',
    'dash.uploadResult': 'آپلود نتیجه',
    // Business Dashboard
    'biz.home': 'خانه',
    'biz.discover': 'کشف بلاگرها',
    'biz.campaigns': 'کمپین‌ها',
    'biz.applications': 'درخواست‌ها',
    'biz.messages': 'پیام‌ها',
    'biz.analytics': 'آمار',
    'biz.profile': 'پروفایل',
    'biz.welcomeMsg': 'خلاصه فعالیت‌های امروز',
    'biz.activeCampaigns': 'کمپین فعال',
    'biz.totalApplicants': 'درخواست‌دهنده',
    'biz.accepted': 'تأیید شده',
    'biz.pendingReview': 'در انتظار بررسی',
    'biz.quickActions': 'دسترسی سریع',
    'biz.createCampaign': 'ساخت کمپین',
    'biz.reviewApps': 'بررسی درخواست‌ها',
    'biz.discoverBloggers': 'کشف بلاگرها',
    'biz.viewReports': 'مشاهده گزارش',
    'biz.recentActivity': 'فعالیت‌های اخیر',
    'biz.searchBloggers': 'جستجوی بلاگر...',
    'biz.invite': 'دعوت',
    'biz.all': 'همه',
    'biz.draft': 'پیش‌نویس',
    'biz.active': 'فعال',
    'biz.scheduled': 'زمان‌بندی',
    'biz.completed': 'تکمیل',
    'biz.archived': 'آرشیو',
    'biz.viewApplicants': 'مشاهده درخواست‌ها',
    'biz.newApps': 'جدید',
    'biz.underReview': 'در بررسی',
    'biz.shortlisted': 'منتخب',
    'biz.appAccepted': 'تأیید شده',
    'biz.appRejected': 'رد شده',
    'biz.searchMessages': 'جستجوی پیام...',
    'biz.typeMessage': 'پیام بنویسید...',
    'biz.totalReach': 'دسترسی کل',
    'biz.responseRate': 'نرخ پاسخ',
    'biz.acceptanceRate': 'نرخ پذیرش',
    'biz.completionRate': 'نرخ تکمیل',
    'biz.topCategories': 'دسته‌بندی‌های برتر',
    'biz.topBloggers': 'بلاگرهای برتر',
    'biz.brandInfo': 'اطلاعات برند',
    'biz.security': 'امنیت',
    'biz.notifications': 'اعلان‌ها',
    'biz.team': 'تیم',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.bloggerLogin': 'Blogger Login',
    'nav.businessLogin': 'Business Login',
    'nav.adminEntry': 'Admin Entry',
    'hero.title': 'Smart Connection Between Bloggers & Brands',
    'hero.subtitle': 'Direct, secure, no middleman collaboration',
    'hero.bloggerCard': 'Blogger Login',
    'hero.businessCard': 'Business Login',
    'hero.adminCard': 'Admin Entry',
    'hero.bloggerDesc': 'Create your profile and collaborate with brands',
    'hero.businessDesc': 'Find the right blogger for your campaign',
    'hero.adminDesc': 'Temporary access for dashboard preview',
    'stats.users': 'Active Users',
    'stats.brands': 'Partner Brands',
    'stats.campaigns': 'Successful Campaigns',
    'how.title': 'How It Works',
    'how.step1.title': 'Discover & Select',
    'how.step1.desc': 'Find the right bloggers and brands for you',
    'how.step2.title': 'Coordinate & Collaborate',
    'how.step2.desc': 'Define terms and reach an agreement',
    'how.step3.title': 'Run Campaign',
    'how.step3.desc': 'Execute and track your campaign results',
    'features.title': 'Platform Features',
    'features.security': 'Full Security',
    'features.securityDesc': 'All data and transactions protected at the highest level',
    'features.analytics': 'Analytics Dashboard',
    'features.analyticsDesc': 'Precise stats and analytics for your campaigns',
    'features.directComm': 'Direct Communication',
    'features.directCommDesc': 'Connect directly with no middleman',
    'features.profile': 'Professional Profile',
    'features.profileDesc': 'Complete professional profile to showcase abilities',
    'about.title': 'About Bloggerha',
    'about.desc': 'Bloggerha is a smart marketplace connecting bloggers and influencers with brands.',
    'about.bloggerBenefit': 'For Bloggers: Sustainable income and access to trusted brands',
    'about.brandBenefit': 'For Brands: Access to a vast network of professional bloggers',
    'contact.title': 'Contact Us',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.success': 'Your message was sent successfully!',
    'footer.quickLinks': 'Quick Links',
    'footer.contactInfo': 'Contact Info',
    'footer.email': 'info@bloggerha.com',
    'footer.phone': '+98-21-12345678',
    'footer.address': 'Tehran, Iran',
    'footer.copyright': '© 2025 Bloggerha. All rights reserved.',
    'footer.newsletter': 'Message Admin',
    'footer.newsletterPlaceholder': 'Enter your email',
    'footer.newsletterSend': 'Send',
    'register.blogger.title': 'Blogger Registration',
    'register.business.title': 'Business Registration',
    'register.name': 'Full Name',
    'register.email': 'Email',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.description': 'About You',
    'register.instagram': 'Instagram Link',
    'register.category': 'Category',
    'register.submit': 'Register',
    'register.back': 'Back',
    'register.success': 'Registration successful!',
    'register.categories.lifestyle': 'Lifestyle',
    'register.categories.tech': 'Technology',
    'register.categories.food': 'Food & Cooking',
    'register.categories.fashion': 'Fashion',
    'register.categories.travel': 'Travel',
    'register.categories.beauty': 'Beauty & Cosmetics',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.selectRole': 'Who are you?',
    'auth.blogger': 'Blogger',
    'auth.business': 'Business',
    'auth.loginSuccess': 'Login successful!',
    'auth.signupSuccess': 'Signup successful!',
    'auth.logout': 'Logout',
    'auth.or': 'or',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'admin.temp': 'Temporary Access',
    'admin.title': 'Which dashboard would you like to enter?',
    'admin.subtitle': 'This access is only for design preview',
    'admin.bloggerDash': 'Enter Blogger Dashboard',
    'admin.bloggerDesc': 'Preview the influencer dashboard',
    'admin.businessDash': 'Enter Business Dashboard',
    'admin.businessDesc': 'Preview the brand dashboard',
    'dash.greeting': 'Hello,',
    'dash.welcomeMsg': 'New opportunities await you!',
    'dash.home': 'Home',
    'dash.explore': 'Explore',
    'dash.campaigns': 'Campaigns',
    'dash.profile': 'Profile',
    'dash.currentInvite': 'Current Invite',
    'dash.accept': 'Accept',
    'dash.decline': 'Decline',
    'dash.invitations': 'Invitations',
    'dash.toConfirm': 'To Confirm',
    'dash.toVisit': 'To Visit',
    'dash.completed': 'Completed',
    'dash.featured': 'Featured Campaigns',
    'dash.pending': 'Pending',
    'dash.accepted': 'Accepted',
    'dash.scheduled': 'Scheduled',
    'dash.rejected': 'Rejected',
    'dash.noData': 'No data yet',
    'dash.filters': 'Filters',
    'dash.category': 'Category',
    'dash.location': 'Location',
    'dash.editProfile': 'Edit Profile',
    'dash.save': 'Save',
    'dash.bio': 'Bio',
    'dash.instagram': 'Instagram',
    'dash.engagement': 'Engagement',
    'dash.profileHealth': 'Profile Health',
    'dash.performance': 'Performance',
    'dash.followers': 'Followers',
    'dash.responseRate': 'Response Rate',
    'dash.profileScore': 'Profile Score',
    'dash.applyNow': 'Apply',
    'dash.searchCampaigns': 'Search campaigns...',
    'dash.confirmAttendance': 'Confirm Attendance',
    'dash.uploadResult': 'Upload Result',
    'biz.home': 'Home',
    'biz.discover': 'Discover',
    'biz.campaigns': 'Campaigns',
    'biz.applications': 'Applications',
    'biz.messages': 'Messages',
    'biz.analytics': 'Analytics',
    'biz.profile': 'Profile',
    'biz.welcomeMsg': "Today's activity summary",
    'biz.activeCampaigns': 'Active Campaigns',
    'biz.totalApplicants': 'Total Applicants',
    'biz.accepted': 'Accepted',
    'biz.pendingReview': 'Pending Review',
    'biz.quickActions': 'Quick Actions',
    'biz.createCampaign': 'Create Campaign',
    'biz.reviewApps': 'Review Apps',
    'biz.discoverBloggers': 'Discover Bloggers',
    'biz.viewReports': 'View Reports',
    'biz.recentActivity': 'Recent Activity',
    'biz.searchBloggers': 'Search bloggers...',
    'biz.invite': 'Invite',
    'biz.all': 'All',
    'biz.draft': 'Draft',
    'biz.active': 'Active',
    'biz.scheduled': 'Scheduled',
    'biz.completed': 'Completed',
    'biz.archived': 'Archived',
    'biz.viewApplicants': 'View Applicants',
    'biz.newApps': 'New',
    'biz.underReview': 'Under Review',
    'biz.shortlisted': 'Shortlisted',
    'biz.appAccepted': 'Accepted',
    'biz.appRejected': 'Rejected',
    'biz.searchMessages': 'Search messages...',
    'biz.typeMessage': 'Type a message...',
    'biz.totalReach': 'Total Reach',
    'biz.responseRate': 'Response Rate',
    'biz.acceptanceRate': 'Acceptance Rate',
    'biz.completionRate': 'Completion Rate',
    'biz.topCategories': 'Top Categories',
    'biz.topBloggers': 'Top Bloggers',
    'biz.brandInfo': 'Brand Info',
    'biz.security': 'Security',
    'biz.notifications': 'Notifications',
    'biz.team': 'Team',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('fa');
  const dir = lang === 'fa' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  const toggleLang = useCallback(() => {
    setLang(prev => prev === 'fa' ? 'en' : 'fa');
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang][key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};
